/* ============================================================
 * story.js —— 剧本
 * ------------------------------------------------------------
 * 结构（三幕）：
 *   第一幕 序章          prologue
 *   第二幕 A线（拆信）    read_*      —— 对抗 / 中点 / 最黑暗时刻
 *         B线（回信）     write_*     —— 对抗 / 中点 / 最黑暗时刻
 *         C线（离开）     leave_*     —— 对抗（回忆反差）/ 抉择
 *   第三幕 结局           ending_*
 *
 * 指令速查（改剧本只需要动这个文件）：
 *   { bg: '名字' }                        切换背景
 *   { bgm: '名字' } / { bgm: null }        切换 / 停止 BGM
 *   { se: '名字' }                         播放音效
 *   { show: '角色id', pose: '表情', at: 'left|center|right' }
 *   { hide: '角色id' } / { clear: true }   隐藏立绘 / 清空所有立绘
 *   { fx: 'shake' | 'flash' }              画面特效
 *   { weather: 'rain' | 'sakura' | 'stars' | null }  天气层
 *   { t: '旁白文字' }                      旁白（无名字框）
 *   { say: '角色名', text: '……', pose: '表情', style: 'letter' }
 *   { choice: { q: '问题', options: [ { text:'…', set:{...}, goto:'标签' } ] } }
 *   { branch: [ [ (s)=>条件, '标签A' ], '标签B' ] }   按变量分支
 *   { set: { 变量名: 值 } }
 *   { card: '第一章 · 回声' }               章节标题卡
 *   { jump: '标签' }
 *   { end: '结局key' }
 *
 * 可用资源：
 *   bg    corridor_dusk / observatory / starfield / classroom_rain /
 *         rooftop_night / gate_morning / archive_room / observatory_night /
 *         rooftop_dawn / mailbox_corner / library_dusk / lawn_summer
 *   char  chenyu(normal/surprise/sad/smile/angry)
 *         hoshi (normal/surprise/sad/smile/cry)
 *         suhe  (normal/smile/sad)
 *   bgm   dusk / night / warm / mystic / tense / morning / ending
 *   se    click / chime / paper / mailbox / heartbeat / select
 * ============================================================ */
const STORY = {

  title: '星屑信箱',
  subtitle: 'Stardust Mailbox',
  author: '一个关于"等待"的故事',
  start: 'prologue',

  /* ---------------- 结局表（用于结局画廊） ---------------- */
  endings: {
    echo:       { name: '星屑回响',   tag: '真结局',   desc: '你寄出的信，在三年后的同一个夜里，被读到了。', star: true },
    beyond:     { name: '星屑之外',   tag: '隐藏结局', desc: '你替所有人把等待结清了——包括你自己。' },
    unsent:     { name: '寄不出的信', tag: '温柔结局', desc: '信投进去了。只是这一次，没有人回答。' },
    unsigned:   { name: '未署名的夏天', tag: '另一种结局', desc: '你读到了别人的过去，于是成了下一个守箱人。' },
    closeddoor: { name: '关上的门',   tag: '通常结局', desc: '什么都没有发生。这才是大部分夏天的样子。' }
  },

  /* ---------------- 场景 ---------------- */
  scenes: {

    /* ============================================================
     * 第一幕 · 序章
     * 节拍：开场画面 → 主题陈述 → 催化事件 → 争论 → 进入第二幕
     * ============================================================ */
    prologue: [
      { bg: 'corridor_dusk', bgm: 'dusk' },
      { card: '序章 · 六月的旧校舍' },
      { t: '六月末的旧校舍，空气里全是灰尘、和晒了一整天太阳的木头味道。' },
      { t: '再有三个月，这栋一九七八年建成的楼就会被推平。校方叫它危楼，我们叫它青春。' },
      { t: '楼道尽头那扇窗开着，风把光切成一条一条，铺在磨得发亮的水磨石地上。' },
      { show: 'chenyu', pose: 'normal', at: 'center' },
      { say: '陈屿', text: '喂，林砚。你认真的？这楼明年就拆了，你还要上来收拾东西？' },
      { say: '林砚', text: '钥匙在我这儿。总得有个人来关一次门。' },
      { say: '陈屿', text: '……行吧。' },
      { say: '陈屿', text: '不过你听见没有？三楼有声音。像有人在拖什么东西。', pose: 'surprise' },
      { say: '林砚', text: '是风。旧楼的窗户关不严。' },
      { say: '陈屿', text: '风不会有节奏。', pose: 'sad' },
      { t: '陈屿是摄影社的。他习惯用取景框代替眼睛——' },
      { t: '可他举着相机的时候，镜头盖一直没摘。' },
      { say: '林砚', text: '……我是天文社最后一个社员。' },
      { say: '林砚', text: '三年前社团就废了，名单上只剩一个名字。' },
      { say: '陈屿', text: '天文社？那个社团不是早就……' },
      { say: '陈屿', text: '等等。你说"最后一个"。那倒数第二个是谁？', pose: 'surprise' },
      { t: '我没有回答。' },
      { t: '三年前我初一。社长是个初三的学姐，叫苏禾。' },
      { t: '她教我认猎户座，教我把望远镜的目镜擦干净，教我——' },
      { t: '在所有人都低头赶路的时候，记得抬头。' },
      { t: '后来她毕业了。' },
      { t: '毕业那天，她没来拍照。' },
      { se: 'chime' },
      { t: '顶楼天文台的门后，有一点光。' },
      { t: '不是灯。是那种……从铁皮缝里漏出来的、会呼吸的光。' },
      { bg: 'observatory', bgm: 'night' },
      { t: '天文台圆顶的正中央开了一扇天窗。' },
      { t: '下午四点半的太阳斜斜地切进来，正好落在房间角落的一个铁箱子上。' },
      { say: '陈屿', text: '……这玩意儿是什么时候在这儿的？', pose: 'surprise' },
      { t: '那是一个锈掉的旧信箱。绿色的漆掉得只剩斑块。' },
      { t: '投信口下面贴着一张褪色的纸：' },
      { t: '【星屑信箱 · 投信请注明年份】', style: 'letter' },
      { say: '陈屿', text: '星屑信箱？谁取的名字。中二。', pose: 'normal' },
      { say: '陈屿', text: '等等——投信口没锁。里面有东西。' },
      { t: '陈屿伸手进去，掏出一个牛皮纸信封。' },
      { t: '信封上没有邮票，没有邮戳。只有一行钢笔字。' },
      { t: '字迹很轻，像是怕把纸划破：' },
      { t: '【致 三年后还愿意抬头看天的人】', style: 'letter' },
      { t: '落款：苏禾。日期：三年前的六月二十日。' },
      { say: '陈屿', text: '……苏禾？那个传说里的天文社社长？', pose: 'surprise' },
      { say: '陈屿', text: '她不是毕业那天就……', pose: 'sad' },
      { say: '林砚', text: '就什么？' },
      { say: '陈屿', text: '……就再也没人见过她了。' },
      { say: '陈屿', text: '学校档案里她那一届的合影，唯独少她一个。', pose: 'sad' },
      { t: '我接过那封信。' },
      { t: '纸很轻，轻得像一片被压平的云。' },
      { t: '三年的灰尘从上面簌簌地掉下来，落在我的鞋尖上。' },
      { t: '信封的左下角有一小片水渍。' },
      { t: '干透了，边缘发黄，像一朵很旧的云。' },
      { se: 'heartbeat' },
      { t: '我忽然想起：三年前的那个下午，下过一场很大的雨。' },
      { choice: {
          q: '——你要怎么做？',
          options: [
            { text: '拆开它。我想知道她写了什么。', set: { route: 'read' }, goto: 'read_1' },
            { text: '写一封信，投进这个信箱。', set: { route: 'write' }, goto: 'write_1' },
            { text: '把信放回去。关上信箱，下楼。', set: { route: 'leave' }, goto: 'leave_1' }
          ]
        } }
    ],

    /* ============================================================
     * 第二幕 · A线（拆信）
     * 节拍：进入新世界 → 主题副线(陈屿) → 中点转折 → 敌收紧 →
     *       一败涂地 → 灵魂黑夜 → 抉择
     * ============================================================ */

    /* --- ① 进入新世界：先弄清这封信是什么 --- */
    read_1: [
      { card: '第一章 · 别人的过去' },
      { t: '信封的封口只用了一点点胶水。' },
      { t: '像是写信的人，自己也拿不定主意要不要封上。' },
      { se: 'paper' },
      { t: '我把它拆开了。' },
      { bg: 'classroom_rain', bgm: 'tense', weather: 'rain' },
      { t: '信纸是从天文社的观测日志上撕下来的，背面还印着表格。' },
      { t: '日期一栏写着：六月二十日。天气一栏写着：雨。' },
      { t: '「如果你打开了这封信，说明这个世界上还有人愿意抬头。」', style: 'letter' },
      { t: '「我是苏禾。三年后的你好——虽然我不知道你会是谁。」', style: 'letter' },
      { t: '「我在毕业那天，做了一件很傻的事。我把自己写进了这个信箱。」', style: 'letter' },
      { t: '「你没看错。不是一封信，是我。」', style: 'letter' },
      { t: '「我很害怕。」', style: 'letter' },
      { t: '「我害怕三年以后，天文社会被拆掉；」', style: 'letter' },
      { t: '「害怕那些我背下来的星名，会被忘掉；」', style: 'letter' },
      { t: '「更害怕——」', style: 'letter' },
      { t: '「更害怕那个总跟在我身后的小学弟，会变成一个不再看天的大人。」', style: 'letter' },
      { t: '后面的字被水浸过，晕开了。' },
      { t: '不知道是那天的雨，还是别的什么。' },
      { t: '「所以如果你读到这里，请替我回答一个问题：」', style: 'letter' },
      { t: '「天顶那颗星——我给它起名叫星屑的那颗——还在吗？」', style: 'letter' },
      { hide: 'chenyu' },
      { bg: 'observatory', bgm: 'mystic' },
      { say: '陈屿', text: '林砚？你脸色很难看。', pose: 'sad' },
      { show: 'chenyu', pose: 'sad', at: 'center' },
      { say: '林砚', text: '……陈屿。三年前，苏禾学姐毕业那天，是不是下过雨？' },
      { say: '陈屿', text: '你怎么知道？那天暴雨，整栋楼都停了电。', pose: 'surprise' },
      { say: '陈屿', text: '我们困在教室到天黑，谁都走不了。', pose: 'normal' },
      { say: '林砚', text: '信纸上的水痕，是那天的雨。' },
      { say: '林砚', text: '也就是说——这封信从写下到今天，一次都没有被打开过。' },
      { say: '陈屿', text: '那说明什么？', pose: 'surprise' },
      { say: '林砚', text: '说明它一直在等一个会来开门的人。' },
      { say: '陈屿', text: '……你在说你自己吧。', pose: 'sad' },
      { say: '林砚', text: '我在说我们俩。' },
      { say: '林砚', text: '你今天为什么会跟我上来？' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { say: '陈屿', text: '因为我也想来关门。', pose: 'normal' },
      { say: '陈屿', text: '摄影社的活动室在四楼。我一次都没进去过。' },
      { jump: 'read_chenyu_1' }
    ],

    /* --- ② 主题副线：陈屿的裂缝 --- */
    read_chenyu_1: [
      { t: '陈屿把相机举起来，对着天窗。' },
      { t: '我这才注意到，镜头盖一直没摘。' },
      { say: '林砚', text: '你的镜头盖。' },
      { say: '陈屿', text: '……啊。', pose: 'surprise' },
      { t: '他愣了一下，像是被人叫醒。' },
      { say: '陈屿', text: '习惯了。取景框里的东西，我从来不看。', pose: 'sad' },
      { say: '林砚', text: '那你拍什么？' },
      { say: '陈屿', text: '拍"我拍过"。' },
      { say: '陈屿', text: '只要快门响过，就算发生过。照片洗出来是什么样，我不在乎。', pose: 'sad' },
      { say: '林砚', text: '……为什么？' },
      { say: '陈屿', text: '因为我怕看清楚。' },
      { say: '陈屿', text: '看清楚就会发现，我拍的东西，没有一样是我真的想要的。', pose: 'sad' },
      { t: '他把相机放到桌上，镜头盖还是没摘。' },
      { say: '陈屿', text: '你知道最烦的是什么吗。' },
      { say: '陈屿', text: '我拍了三年的校舍，可我真的记得的，一场都没有。' },
      { say: '陈屿', text: '我只是一直在按快门。', pose: 'sad' },
      { say: '林砚', text: '那把盖子摘了。' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { say: '陈屿', text: '那你呢？你的望远镜，上一次擦目镜是什么时候？', pose: 'normal' },
      { t: '我没有回答。' },
      { t: '因为答案很难看。' },
      { t: '上一次擦目镜，是三年前，苏禾还在的时候。' },
      { say: '陈屿', text: '看吧。', pose: 'normal' },
      { say: '陈屿', text: '我们是一路货色。' },
      { say: '陈屿', text: '你不敢抬头，我不敢按快门。' },
      { jump: 'read_night' }
    ],

    /* --- ③ 夜晚：查旧校刊，逼近真相 --- */
    read_night: [
      { bg: 'archive_room', bgm: 'mystic' },
      { t: '那封信里有很多我没读懂的东西。' },
      { t: '比如"我把自己写进去"这句话。' },
      { t: '比如她为什么要问一颗星还在不在。' },
      { say: '林砚', text: '档案室还开着。想不想翻点旧东西？' },
      { say: '陈屿', text: '翻什么？', pose: 'surprise' },
      { say: '林砚', text: '三年前的校刊。天文社那次活动，应该有记录。' },
      { t: '档案室的窗户很小，光从那一个口子里挤进来。' },
      { t: '灰尘在光里浮着，像一群不肯落地的星。' },
      { se: 'paper' },
      { t: '我们翻了两摞校刊。' },
      { t: '第三本里，夹着一页手写的活动记录。' },
      { t: '「六月十九日 晴。观测：天顶偏南天区。记录人：苏禾。」', style: 'letter' },
      { t: '「注：今日发现一颗亮度变化异常的星。周期约三年。暂命名为——星屑。」', style: 'letter' },
      { say: '陈屿', text: '……她给一颗星起了名字。', pose: 'surprise' },
      { say: '林砚', text: '嗯。而且她标注了周期。' },
      { say: '林砚', text: '约三年。' },
      { t: '三年。' },
      { t: '正好是她消失到现在的时间。' },
      { say: '陈屿', text: '巧合吧？', pose: 'sad' },
      { say: '林砚', text: '希望是。' },
      { t: '我把那张活动记录折起来，放进口袋。' },
      { t: '翻到最后一页的时候，我停住了。' },
      { t: '那是一张天文社的合影。' },
      { t: '照片上一共四个人。三个笑着，一个站在最边上，眼睛看着镜头外面。' },
      { t: '站在最边上的那个，是苏禾。' },
      { t: '她看的方向，是照片外面——' },
      { t: '也就是，拍照片的人站的位置。' },
      { say: '陈屿', text: '……她为什么不看镜头？', pose: 'sad' },
      { say: '林砚', text: '因为她在看拍照的人。' },
      { say: '林砚', text: '陈屿，这张照片是谁拍的？' },
      { say: '陈屿', text: '……', pose: 'surprise' },
      { say: '陈屿', text: '校刊下面有小字。' },
      { t: '我把照片翻过来。' },
      { t: '背面用铅笔写着一行很小的字：' },
      { t: '【摄影：苏禾（自拍）】', style: 'letter' },
      { se: 'heartbeat' },
      { say: '林砚', text: '……自拍？' },
      { say: '林砚', text: '那她怎么会在照片里？' },
      { fx: 'shake' },
      { say: '陈屿', text: '林砚。', pose: 'surprise' },
      { say: '陈屿', text: '你说过，照片上少了她一个。', pose: 'surprise' },
      { say: '陈屿', text: '可是这张照片里，她在。' },
      { say: '陈屿', text: '而且是唯一一张——她站在画面里的。', pose: 'surprise' },
      { t: '两张照片，一张有她，一张没有她。' },
      { t: '同一个下午，同一群人。' },
      { say: '林砚', text: '……她在选。' },
      { say: '林砚', text: '她在选自己要不要留在这张照片里。' },
      { jump: 'read_midpoint' }
    ],

    /* --- ④ 中点转折：真相 --- */
    read_midpoint: [
      { bg: 'observatory_night', bgm: 'tense', weather: 'stars' },
      { t: '那天晚上我们又回了天文台。' },
      { t: '不是为了找东西。是两个人都不敢一个人待着。' },
      { t: '圆顶的天窗开着，银河横在正中央。' },
      { say: '陈屿', text: '你说，一个人要怎么"把自己写进一封信"？', pose: 'sad' },
      { say: '林砚', text: '不知道。' },
      { say: '陈屿', text: '那她为什么问那颗星还在不在？', pose: 'sad' },
      { say: '陈屿', text: '她不是自己看的吗。' },
      { t: '我站在望远镜前，忽然明白了。' },
      { t: '她问的不是"星还在不在"。' },
      { say: '林砚', text: '她问的是——' },
      { say: '林砚', text: '"还有没有人，从我站过的地方抬头。"' },
      { se: 'chime' },
      { t: '她的手稿就是在这一刻自己出现的。' },
      { t: '不是从柜子里掉出来。' },
      { t: '是从那台望远镜的目镜上，慢慢浮出来的。' },
      { fx: 'flash' },
      { show: 'suhe', pose: 'sad', at: 'right' },
      { say: '苏禾', text: '你终于想明白了。' },
      { say: '陈屿', text: '——!!', pose: 'surprise' },
      { say: '林砚', text: '学姐。' },
      { say: '苏禾', text: '我不是学姐了。' },
      { say: '苏禾', text: '学姐是三年前的她。我是她留在目镜上的那点指纹。', pose: 'sad' },
      { say: '苏禾', text: '她擦目镜很认真。擦完的最后一次，指纹留在了镜片上。' },
      { say: '苏禾', text: '信箱收的不是信，是"留下来的一点点东西"。' },
      { say: '苏禾', text: '愿望、指纹、没说出口的话——都可以。' },
      { say: '林砚', text: '那她本人呢？她在哪儿？' },
      { say: '苏禾', text: '……', pose: 'sad' },
      { say: '苏禾', text: '你拆开的那封信，就是她。' },
      { say: '苏禾', text: '她把三年份的自己，全都写进去了。' },
      { hide: 'chenyu' },
      { show: 'suhe', pose: 'sad', at: 'center' },
      { say: '苏禾', text: '所以那封信只能在信封里活着。' },
      { say: '苏禾', text: '一旦被拆开——', pose: 'sad' },
      { say: '苏禾', text: '读到最后一个字，她就没有了。' },
      { fx: 'shake' },
      { t: '我低头看手里的信。' },
      { t: '最后一行字，正在变淡。' },
      { say: '林砚', text: '等等——' },
      { say: '林砚', text: '我不该拆的。' },
      { say: '苏禾', text: '不。你必须拆。', pose: 'normal' },
      { say: '苏禾', text: '不被读到的信，不算寄到。' },
      { say: '苏禾', text: '她等了三年，等的就是有人拆开。' },
      { say: '苏禾', text: '——哪怕代价是她消失。', pose: 'sad' },
      { say: '林砚', text: '这不公平。' },
      { say: '苏禾', text: '世界上所有的等待都不公平。', pose: 'sad' },
      { say: '苏禾', text: '所以人才要一边等，一边学着不算计。', pose: 'normal' },
      { set: { knowTruth: true } },
      { jump: 'read_cost' }
    ],

    /* --- ⑤ 敌人收紧 / 一败涂地：代价 --- */
    read_cost: [
      { bg: 'rooftop_dawn', bgm: 'tense', weather: null },
      { card: '第二章 · 代价' },
      { t: '那天之后，我每天都去天文台。' },
      { t: '我怕那封信消失。' },
      { t: '它确实在消失。' },
      { t: '每天少一个字。' },
      { t: '第三天，「如果我读到这里」的"我"不见了。' },
      { t: '第五天，「请替我回答」只剩下"回答"。' },
      { say: '陈屿', text: '你不能这样。', pose: 'angry' },
      { show: 'chenyu', pose: 'angry', at: 'left' },
      { say: '陈屿', text: '你已经五天没去上课了！', pose: 'angry' },
      { say: '林砚', text: '它少一个字，她就少一点。' },
      { say: '陈屿', text: '那是她自己的选择！', pose: 'angry' },
      { say: '陈屿', text: '她选了把信留在这儿，就是要给三年后的人看。' },
      { say: '陈屿', text: '你看完了。结束。', pose: 'angry' },
      { say: '林砚', text: '没有结束。' },
      { say: '林砚', text: '信里那个问题，我还没有回答。' },
      { say: '陈屿', text: '什么？' , pose: 'surprise' },
      { say: '林砚', text: '"那颗星还在吗。"' },
      { say: '林砚', text: '她要的不是"看过"。她要的是"回答"。' },
      { say: '陈屿', text: '那你就回答啊！站在天台上喊一声不就行了！', pose: 'angry' },
      { say: '林砚', text: '……' },
      { say: '林砚', text: '我喊过了。' },
      { say: '林砚', text: '每一个晚上。' },
      { say: '林砚', text: '没有回声。' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { t: '陈屿沉默了很久。' },
      { say: '陈屿', text: '那你打算怎么办。', pose: 'sad' },
      { t: '我摊开信纸。' },
      { t: '上面只剩最后一行字。' },
      { t: '「——还在吗？」', style: 'letter' },
      { t: '我忽然想起一件事。' },
      { t: '这封信，是写给"三年后还愿意抬头看天的人"。' },
      { say: '林砚', text: '陈屿。' },
      { say: '林砚', text: '你带相机了吗。' },
      { say: '陈屿', text: '……带了。', pose: 'surprise' },
      { say: '林砚', text: '帮我拍一张照片。' },
      { say: '林砚', text: '我要回答她。' },
      { jump: 'read_answer' }
    ],

    /* --- ⑥ 灵魂黑夜 → 抉择 --- */
    read_answer: [
      { bg: 'rooftop_night', bgm: 'mystic', weather: 'stars' },
      { t: '天台。夜里十一点。' },
      { t: '天顶偏南一点，那颗星很亮。' },
      { t: '我在天台中央站好，抬头。' },
      { say: '陈屿', text: '……你确定？', pose: 'sad' },
      { say: '林砚', text: '信箱收的是"留下来的东西"。' },
      { say: '林砚', text: '那我留一张照片。' },
      { say: '林砚', text: '一张我抬着头的照片。' },
      { se: 'chime' },
      { t: '快门响的那一瞬间，风停了。' },
      { fx: 'flash' },
      { show: 'hoshi', pose: 'cry', at: 'center' },
      { t: '「——找到了。」' },
      { t: '声音不是从身后，也不是从照片里。' },
      { t: '是从我自己的胸腔里。' },
      { say: '？？？', text: '谢谢你，林砚。' },
      { say: '林砚', text: '……你是谁？' },
      { say: '？？？', text: '我是它。', pose: 'normal' },
      { say: '？？？', text: '或者你可以叫我——"回信"。' },
      { say: '？？？', text: '三年里，这个信箱收过很多封信，也回过很多次。' },
      { say: '？？？', text: '但不是每个人都会回答。' },
      { say: '？？？', text: '大部分人拆开，读完，然后把它放进抽屉。', pose: 'sad' },
      { say: '？？？', text: '那样的话，写信的人就一直没有寄到。' },
      { say: '？？？', text: '你不一样。你回答了。' },
      { say: '林砚', text: '那她呢？她还在吗？' },
      { say: '？？？', text: '……', pose: 'sad' },
      { say: '？？？', text: '你回答了一个问题，信封就补回来一个字。', pose: 'normal' },
      { say: '？？？', text: '但她的信有三百二十七个字。' },
      { say: '？？？', text: '你回答一次，只能补一个字。', pose: 'sad' },
      { say: '林砚', text: '……三百二十七次。' },
      { say: '？？？', text: '而且每次回答都要付一点东西。' },
      { say: '？？？', text: '一张照片，一次等待，一段你不会再记得的时间。' },
      { say: '？？？', text: '你想清楚了吗？', pose: 'normal' },
      { choice: {
          q: '——你要怎么回答？',
          options: [
            { text: '一个字一个字，把她的信补回来。哪怕要很多年。', set: { resolve: 'restore' }, goto: 'read_restore' },
            { text: '不补了。有些话说到这里就够了。', set: { resolve: 'letgo' }, goto: 'read_letgo' },
            { text: '把它交给我。我留下来当守箱人。', set: { resolve: 'keeper' }, goto: 'read_keeper' }
          ]
        } }
    ],

    /* --- 结局分支 A1：一个字一个字补回来 --- */
    read_restore: [
      { bg: 'observatory_night', bgm: 'warm' },
      { say: '？？？', text: '……你知道这意味着什么吗。', pose: 'surprise' },
      { say: '林砚', text: '知道。' },
      { say: '林砚', text: '从今天起，我每天来一次。' },
      { say: '林砚', text: '写一句话，投进去。' },
      { say: '？？？', text: '那很慢。', pose: 'sad' },
      { say: '林砚', text: '她等了三年。我不急。' },
      { hide: 'hoshi' },
      { show: 'chenyu', pose: 'sad', at: 'left' },
      { say: '陈屿', text: '……我帮你。', pose: 'sad' },
      { say: '林砚', text: '什么？' },
      { say: '陈屿', text: '我会拍照。' },
      { say: '陈屿', text: '你写一句话，我配一张照片。', pose: 'normal' },
      { say: '陈屿', text: '三百二十七张。我拍得起。' },
      { t: '他摘下了镜头盖。' },
      { t: '三年来第一次。' },
      { se: 'chime' },
      { set: { companion: true } },
      { jump: 'ending_echo_pre' }
    ],

    /* --- 结局分支 A2：放手 --- */
    read_letgo: [
      { bg: 'rooftop_dawn', bgm: 'morning' },
      { say: '？？？', text: '……', pose: 'sad' },
      { say: '？？？', text: '你是第一个说"到这里就够了"的人。', pose: 'sad' },
      { say: '林砚', text: '因为她写信的时候，不是要一个结果。' },
      { say: '林砚', text: '她只是想在三年后，有个人知道她抬头看过。' },
      { say: '林砚', text: '我知道了。' },
      { say: '林砚', text: '这就够了。' },
      { say: '？？？', text: '……那你想留一句话给她吗。', pose: 'normal' },
      { say: '林砚', text: '嗯。' },
      { t: '我在信纸的空白处，写下最后一行：' },
      { t: '「星还在。我也还在。你不用再等了。」', style: 'letter' },
      { se: 'paper' },
      { fx: 'flash' },
      { t: '信纸自己折了起来，折成一封新的信。' },
      { t: '滑进了投信口。' },
      { jump: 'ending_unsent_pre' }
    ],

    /* --- 结局分支 A3：当守箱人（对应 unsigned） --- */
    read_keeper: [
      { show: 'hoshi', pose: 'cry', at: 'center' },
      { say: '？？？', text: '……留下来？', pose: 'surprise' },
      { say: '林砚', text: '信箱要有一个人守着。' },
      { say: '林砚', text: '不然下一个拆信的人，还是不知道该怎么办。' },
      { say: '？？？', text: '那你自己呢。', pose: 'sad' },
      { say: '林砚', text: '我会记得她教过我的东西。' },
      { say: '林砚', text: '认星、擦目镜、还有——在别人低头的时候抬头。' },
      { say: '？？？', text: '……', pose: 'sad' },
      { say: '？？？', text: '好。', pose: 'normal' },
      { say: '？？？', text: '那从今天起，这件外套归你了。' },
      { t: '我看不见她，但我知道她在笑。' },
      { jump: 'ending_unsigned_pre' }
    ],

    /* ============================================================
     * 第二幕 · B线（回信）
     * 节拍：进入新世界 → 找星图 → 主题副线 → 中点(信箱的规则) →
     *       敌收紧(代价) → 灵魂黑夜 → 抉择
     * ============================================================ */
    write_1: [
      { card: '第一章 · 写给未来的信' },
      { t: '我把那封信放回信箱，合上投信口。' },
      { t: '不是因为不好奇。' },
      { t: '是因为——如果这是她写给三年后的我的，那我得先配得上"三年后的我"这个人。' },
      { say: '陈屿', text: '……你要干嘛？', pose: 'surprise' },
      { say: '林砚', text: '我要写回信。' },
      { say: '陈屿', text: '写给一个可能不存在的人？', pose: 'sad' },
      { say: '林砚', text: '写给一个一定存在过的人。' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { say: '陈屿', text: '你连她长什么样都不知道。' },
      { say: '林砚', text: '我知道她抬头看天的样子。' },
      { bg: 'observatory', bgm: 'night' },
      { t: '天文台的储物柜里还有一叠没用完的观测日志。我撕下一张。' },
      { t: '笔是苏禾留下的那支。' },
      { t: '笔帽上贴着一小块反光贴——她说这样掉在地上也能找得到。' },
      { t: '我拧开笔帽，却不知道该从哪一句写起。' },
      { say: '陈屿', text: '……你手在抖。', pose: 'sad' },
      { say: '林砚', text: '因为我不知道写给谁。' },
      { say: '林砚', text: '写给一个已经不在的人，算是信吗。' },
      { say: '陈屿', text: '算。', pose: 'normal' },
      { say: '陈屿', text: '只要有人读。' },
      { say: '陈屿', text: '……不过你先想清楚要写什么。', pose: 'sad' },
      { say: '陈屿', text: '这种东西，写错了没法改。' },
      { choice: {
          q: '——动笔之前，你要先做什么？',
          options: [
            { text: '先去找她留下的那本手绘星图。我想写准确一点。', set: { starmap: true }, goto: 'write_find' },
            { text: '不用了。现在就写，想到什么写什么。', set: { starmap: false }, goto: 'write_now' }
          ]
        } }
    ],

    /* --- 找星图（获得关键道具 starmap） --- */
    write_find: [
      { bg: 'archive_room', bgm: 'mystic' },
      { se: 'paper' },
      { t: '活动室的柜子最底层，压着一个硬壳文件夹。' },
      { t: '陈屿帮我把它拖出来的时候，灰扬了半间屋子。' },
      { say: '陈屿', text: '咳……这放了多久了。', pose: 'surprise' },
      { t: '里面是一沓手绘星图。' },
      { t: '每一张右下角都写着同一个名字：苏禾。' },
      { t: '她的字很小，很密，像是怕浪费纸。' },
      { t: '前面十几张都是常规天区。猎户座、仙后座、夏季大三角。' },
      { t: '最后一页画的是天顶偏南的一小片天区。' },
      { t: '别的星星都只有坐标。' },
      { t: '唯独其中一颗旁边，用铅笔写着一个名字——' },
      { t: '【星屑】', style: 'letter' },
      { t: '旁边还有一行小字：' },
      { t: '「亮度变化周期：约三年。林砚，记好，别认错。」', style: 'letter' },
      { se: 'chime' },
      { say: '陈屿', text: '……她写了你的名字。', pose: 'surprise' },
      { t: '我盯着那三个字看了很久。' },
      { t: '她的字迹在这里，比别处都要慢。' },
      { t: '像是写这一句的时候，她犹豫过。' },
      { say: '林砚', text: '她本来可以不写。' },
      { say: '林砚', text: '只要写"记好，别认错"就够了。' },
      { say: '陈屿', text: '那她为什么写。', pose: 'sad' },
      { say: '林砚', text: '因为写名字，就是点名。' },
      { say: '林砚', text: '点到名字的人，会来。' },
      { t: '我把星图揣进外套内袋，回到天文台。' },
      { jump: 'write_letter' }
    ],

    write_now: [
      { t: '想太多就写不出来了。' },
      { t: '她以前是这么教我的。' },
      { t: '"观星和写信一样，林砚。"' },
      { t: '"你越想写得漂亮，越写不出真的东西。"' },
      { hide: 'chenyu' },
      { bg: 'rooftop_night', bgm: 'night', weather: 'stars' },
      { t: '我拿着笔，走到天台上。' },
      { t: '没有星图，没有坐标。' },
      { t: '我抬头，凭记忆去找那颗星。' },
      { t: '猎户座的腰带往下，偏南一点点——' },
      { t: '找到了。' },
      { t: '它还在原来的位置。' },
      { t: '我忽然明白，其实我从来没有忘。' },
      { t: '我只是一直假装忘了。' },
      { se: 'chime' },
      { t: '我在天台上把信写完了。' },
      { t: '没有参照任何一张图。' },
      { t: '每一个字，都是我自己记得的。' },
      { set: { fromMemory: true } },
      { jump: 'write_letter' }
    ],

    /* --- 动笔 --- */
    write_letter: [
      { bg: 'observatory', bgm: 'warm' },
      { t: '我在观测日志的背面写下去。字迹比想象中抖。' },
      { t: '「学姐，我是林砚。三年后的林砚。」', style: 'letter' },
      { t: '「天文社确实废了。我确实是最后一个。」', style: 'letter' },
      { t: '「我也确实——差点变成一个不再看天的大人。」', style: 'letter' },
      { t: '「但是那颗星还在。」', style: 'letter' },
      { t: '「我今晚去看过了。它还在原来的位置，亮度变化周期还是约三年。」', style: 'letter' },
      { t: '「你没标错。」', style: 'letter' },
      { t: '「所以你那个问题的答案是：在。一直都在。」', style: 'letter' },
      { t: '「还有一句你没问的，我也写下来——」', style: 'letter' },
      { t: '「我没有变成你害怕的那种大人。」', style: 'letter' },
      { se: 'chime' },
      { t: '写完最后一个字的时候，房间里亮了一下。' },
      { t: '不是灯。是那个锈掉的信箱。' },
      { show: 'hoshi', pose: 'normal', at: 'center' },
      { say: '？？？', text: '……你在写给谁。' },
      { say: '林砚', text: '苏禾学姐？' },
      { say: '？？？', text: '我是信箱的回声。你可以这么叫我。' },
      { say: '？？？', text: '信箱的规则只有一条：' },
      { say: '？？？', text: '一次只能送一封信，写信的人要拿"等待"来换。' },
      { say: '？？？', text: '三年前，有个女孩用自己换了这里的一封信。', pose: 'sad' },
      { say: '？？？', text: '从那以后，她就住在这里了。' },
      { say: '林砚', text: '……她现在在哪儿？' },
      { say: '？？？', text: '在你写的那封信里。', pose: 'smile' },
      { say: '？？？', text: '你每写一个字，她就听得见一次。' },
      { jump: 'write_rule' }
    ],

    /* --- ② 主题副线：陈屿的裂缝（B线版本） --- */
    write_rule: [
      { show: 'chenyu', pose: 'sad', at: 'left' },
      { say: '陈屿', text: '……那我呢。', pose: 'sad' },
      { show: 'hoshi', pose: 'normal', at: 'right' },
      { say: '？？？', text: '你？你只是跟着来的人。' },
      { say: '？？？', text: '信箱不认旁观者。' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { say: '陈屿', text: '林砚，我跟你说件事。', pose: 'sad' },
      { say: '陈屿', text: '三年前那个下午，我也在。', pose: 'sad' },
      { say: '林砚', text: '什么？' },
      { say: '陈屿', text: '毕业那天，我在楼下。' },
      { say: '陈屿', text: '我看见苏禾一个人上了顶楼。' },
      { say: '陈屿', text: '我手里拿着相机。', pose: 'sad' },
      { say: '陈屿', text: '我想叫她一声，问问她要不要拍一张。' },
      { say: '陈屿', text: '但我没叫。', pose: 'sad' },
      { say: '陈屿', text: '因为我怕她拒绝，怕拍出来不好看，怕……', pose: 'sad' },
      { say: '陈屿', text: '怕被记住。', pose: 'sad' },
      { t: '他的镜头盖，还是没摘。' },
      { say: '林砚', text: '所以你后来拍了三年的照片。' },
      { say: '林砚', text: '张张都不看。' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { say: '陈屿', text: '嗯。', pose: 'sad' },
      { say: '陈屿', text: '只要不看，就算没发生。', pose: 'sad' },
      { say: '？？？', text: '……', pose: 'sad' },
      { say: '？？？', text: '你知道信箱为什么在这里吗。', pose: 'normal' },
      { say: '？？？', text: '因为三年前，有个人在顶楼站了很久。' },
      { say: '？？？', text: '她一直在等楼下有人喊她一声。' },
      { say: '？？？', text: '等到最后，她自己走了。' },
      { fx: 'shake' },
      { say: '陈屿', text: '……', pose: 'surprise' },
      { say: '陈屿', text: '那个人是我。', pose: 'sad' },
      { say: '？？？', text: '不。' },
      { say: '？？？', text: '那个人不是你。' },
      { say: '？？？', text: '那个人是"没喊出口的那声"。', pose: 'sad' },
      { say: '？？？', text: '它一直留在这里。', pose: 'sad' },
      { jump: 'write_midpoint' }
    ],

    /* --- ③ 中点转折：信箱的真实规则 --- */
    write_midpoint: [
      { bg: 'observatory_night', bgm: 'tense', weather: 'stars' },
      { hide: 'chenyu' },
      { show: 'hoshi', pose: 'normal', at: 'center' },
      { say: '？？？', text: '现在你知道规则了。' },
      { say: '？？？', text: '这封信一旦投进去，就要等三年。' },
      { say: '？？？', text: '三年里你会毕业、会走远、会忘记今天写下的每一个字。' },
      { say: '？？？', text: '你愿意吗？' },
      { say: '林砚', text: '……等一下。' },
      { say: '林砚', text: '你说"一次只能送一封信"。' },
      { say: '林砚', text: '那么这封信送出去以后，信箱里就空了。' },
      { say: '？？？', text: '……', pose: 'surprise' },
      { say: '林砚', text: '空了以后呢？' },
      { say: '？？？', text: '……', pose: 'sad' },
      { say: '？？？', text: '空了以后，我就没有东西可以读了。', pose: 'sad' },
      { say: '？？？', text: '我读不到的，就会散掉。', pose: 'sad' },
      { fx: 'shake' },
      { say: '林砚', text: '所以你一直劝人写信。' },
      { say: '？？？', text: '……' },
      { say: '林砚', text: '不是为了送到。' },
      { say: '林砚', text: '是为了你自己有东西可读。' },
      { say: '？？？', text: '……对不起。', pose: 'sad' },
      { say: '？？？', text: '我不是坏东西。我只是怕消失。', pose: 'sad' },
      { say: '？？？', text: '一封一封地读别人的信，是我唯一活着的方式。' },
      { say: '？？？', text: '我读了三年，读了四十七封。' },
      { say: '？？？', text: '它们都没有被回答过。', pose: 'sad' },
      { say: '？？？', text: '所以我一直留在这里。' },
      { set: { knowEcho: true } },
      { jump: 'write_cost' }
    ],

    /* --- ④ 敌收紧 / 一败涂地 --- */
    write_cost: [
      { bg: 'mailbox_corner', bgm: 'tense' },
      { card: '第二章 · 四十七封' },
      { t: '回声说完那句话，就安静了。' },
      { t: '我这才发现，我从来没有真的看过它。' },
      { say: '林砚', text: '……四十七封，都在哪里。' },
      { say: '？？？', text: '在这里。', pose: 'sad' },
      { se: 'mailbox' },
      { t: '信箱轻轻响了一声。' },
      { t: '投信口里滑出薄薄的一沓纸。' },
      { t: '不是信。是信的影子。' },
      { t: '每一张都空白的，只留着一个投递的日期。' },
      { t: '最早的一张：三年前的六月二十日。' },
      { t: '就是苏禾投信的那天。' },
      { say: '林砚', text: '……这是学姐那封。' },
      { say: '？？？', text: '是。', pose: 'sad' },
      { say: '？？？', text: '她把信投进来的时候，还没有人读。' },
      { say: '？？？', text: '所以它就变成了一张纸的影子，一直在这里。' },
      { say: '林砚', text: '那其他四十六封呢？' },
      { say: '？？？', text: '都是这些年，有人写、但没人回答的。', pose: 'sad' },
      { say: '？？？', text: '有写给毕业的自己的。有写给去世的猫的。' },
      { say: '？？？', text: '有一封是写给三年前那个没说出口的人。' },
      { say: '林砚', text: '……那是陈屿。' },
      { say: '？？？', text: '是的。', pose: 'sad' },
      { say: '？？？', text: '他去年春天来过一次。' },
      { say: '？？？', text: '在门口站了一个小时，没有进来。' },
      { fx: 'shake' },
      { say: '林砚', text: '他怎么知道这里？' },
      { say: '？？？', text: '因为他一直在查。', pose: 'sad' },
      { say: '？？？', text: '他查了三年。', pose: 'sad' },
      { say: '？？？', text: '只是想找个地方，把"没喊出的那声"说出来。' },
      { t: '我握着那张写给陈屿的空白影子。' },
      { t: '纸很薄，轻得像什么都没写。' },
      { say: '林砚', text: '……我要把这四十七封，全都回答掉。' },
      { say: '？？？', text: '不行。', pose: 'surprise' },
      { say: '？？？', text: '一封一封回答，你要用掉的时间，是你的一辈子。', pose: 'sad' },
      { say: '？？？', text: '而且——', pose: 'sad' },
      { say: '？？？', text: '你回答一封，我就少一封可读。', pose: 'sad' },
      { say: '？？？', text: '你在拆我自己。' },
      { t: '我说不出话。' },
      { t: '这就是最难的地方。' },
      { t: '我帮了写信的人，就等于杀了读信的人。' },
      { jump: 'write_choice' }
    ],

    /* --- ⑤ 灵魂黑夜 → 抉择 --- */
    write_choice: [
      { bg: 'rooftop_dawn', bgm: 'mystic', weather: null },
      { t: '我在天台坐了一整夜。' },
      { t: '陈屿陪着我。' },
      { show: 'chenyu', pose: 'sad', at: 'left' },
      { say: '陈屿', text: '……你想好了吗。', pose: 'sad' },
      { say: '林砚', text: '想好了一半。' },
      { say: '陈屿', text: '哪一半。', pose: 'sad' },
      { say: '林砚', text: '我要把信投进去。' },
      { say: '林砚', text: '我要让那四十七个人，一个一个被回答。' },
      { say: '陈屿', text: '那回声呢。', pose: 'sad' },
      { say: '林砚', text: '……' },
      { say: '林砚', text: '我不知道。' },
      { t: '天开始亮了。' },
      { t: '那颗星在天边淡下去。' },
      { show: 'hoshi', pose: 'cry', at: 'right' },
      { say: '？？？', text: '……天亮了。', pose: 'sad' },
      { say: '？？？', text: '我要走了。' },
      { say: '林砚', text: '等一下——' },
      { say: '？？？', text: '不。该做决定了。', pose: 'normal' },
      { say: '？？？', text: '你要写信，还是写我。' },
      { say: '？？？', text: '这两个只能选一个。', pose: 'sad' },
      { say: '？？？', text: '因为信箱一次只送一封信。', pose: 'sad' },
      { choice: {
          q: '——太阳升起来之前，你要投哪一封？',
          options: [
            { text: '写给苏禾的那封。我说过要给她的答案。', set: { choice_letter: 'suhe' }, goto: 'write_pick_suhe' },
            { text: '写给回声的那封。让它也被读到一次。', set: { choice_letter: 'echo' }, goto: 'write_pick_echo' },
            { text: '写给陈屿的那声"没说出口"。', set: { choice_letter: 'chenyu' }, goto: 'write_pick_chenyu' }
          ]
        } }
    ],

    write_pick_suhe: [
      { se: 'mailbox' },
      { fx: 'flash' },
      { t: '我把写着苏禾名字的那张纸，折进信封。' },
      { say: '？？？', text: '……好。', pose: 'sad' },
      { say: '？？？', text: '那就照你写的来。' },
      { t: '信纸滑进投信口，发出很轻的一声。' },
      { t: '像一口很深很深的井，接住了一颗石子。' },
      { say: '？？？', text: '收到了。', pose: 'smile' },
      { say: '？？？', text: '三年后的今天，会有人打开它。' },
      { say: '林砚', text: '会是谁？' },
      { say: '？？？', text: '谁知道呢。也许是另一个，还愿意抬头看天的小孩。' },
      { branch: [
          [function (s) { return s.starmap === true; }, 'write_pick_suhe_map'],
          'write_pick_suhe_free'
        ] }
    ],

    /* 拿了星图：坐标精确，信是"查证过"的，回声因此有了可传下去的凭据 → 真结局 */
    write_pick_suhe_map: [
      { t: '走出天文台的时候，我把那张手绘星图留在了信箱顶上。' },
      { t: '压在一块石头下面，怕被风吹走。' },
      { say: '？？？', text: '……你把图留下做什么。', pose: 'sad' },
      { say: '林砚', text: '因为信箱要有坐标。' },
      { say: '林砚', text: '不然三年后的人找到它，也不知道该往哪儿看。' },
      { say: '？？？', text: '……', pose: 'surprise' },
      { say: '？？？', text: '你把"她"留给我了。', pose: 'sad' },
      { say: '林砚', text: '不是留给你。' },
      { say: '林砚', text: '是留给你、和下一个来的人，一起用。' },
      { t: '信箱没有回答。' },
      { t: '但那天晚上，我抬头的时候，那颗星比平时亮了一点。' },
      { se: 'chime' },
      { set: { gaveMap: true } },
      { jump: 'ending_echo_pre' }
    ],

    /* 没拿星图，凭记忆写完：信是真的，但少了坐标，只能算寄出，等不到回音 → 温柔结局 */
    write_pick_suhe_free: [
      { t: '我没有留下别的东西。' },
      { t: '只有那封信。' },
      { say: '？？？', text: '……就这样？', pose: 'surprise' },
      { say: '林砚', text: '嗯。' },
      { say: '林砚', text: '信本来就是这样的东西。' },
      { say: '林砚', text: '寄出去的时候，没人知道会不会有人收。' },
      { say: '？？？', text: '……', pose: 'sad' },
      { say: '？？？', text: '那你为什么还写。' },
      { say: '林砚', text: '因为写，是我的事。' },
      { say: '林砚', text: '收到收不到，是它的事。' },
      { t: '我锁上门，下楼。' },
      { t: '楼道的声控灯一层一层地亮起来，又一层一层地灭下去。' },
      { t: '像一条我走过很多次的路。' },
      { jump: 'ending_unsent_pre' }
    ],

    write_pick_echo: [
      { se: 'mailbox' },
      { fx: 'flash' },
      { t: '我没有写信。' },
      { t: '我把那张空白的影子纸，投了进去。' },
      { say: '？？？', text: '……这是我的。', pose: 'surprise' },
      { say: '林砚', text: '对。' },
      { say: '林砚', text: '你读了三年别人的信。' },
      { say: '林砚', text: '这次换你被读一次。' },
      { say: '？？？', text: '……', pose: 'cry' },
      { say: '？？？', text: '可是里面是空的。', pose: 'cry' },
      { say: '林砚', text: '不空。' },
      { say: '林砚', text: '上面有三年，四十七个日期。' },
      { say: '林砚', text: '那是你活过的证据。' },
      { hide: 'hoshi' },
      { fx: 'flash' },
      { t: '回声没有回答。' },
      { t: '但信箱亮了一下，比之前任何一次都亮。' },
      { t: '然后安静下来。' },
      { set: { sentEcho: true } },
      { jump: 'ending_beyond_pre' }
    ],

    write_pick_chenyu: [
      { show: 'chenyu', pose: 'surprise', at: 'left' },
      { say: '陈屿', text: '……写给我？', pose: 'surprise' },
      { say: '林砚', text: '写给三年前那个没喊出口的你。' },
      { say: '林砚', text: '它在这儿留了三年。该回家了。' },
      { se: 'mailbox' },
      { fx: 'flash' },
      { t: '陈屿没有拦我。' },
      { t: '他只是慢慢地把相机举起来。' },
      { t: '这次，他摘了镜头盖。' },
      { se: 'chime' },
      { t: '快门响的时候，我看到信箱上浮出一行很淡的字。' },
      { t: '「——谢谢你。」', style: 'letter' },
      { say: '陈屿', text: '……', pose: 'smile' },
      { say: '陈屿', text: '林砚。', pose: 'smile' },
      { say: '陈屿', text: '我好像终于拍到东西了。', pose: 'smile' },
      { set: { freedChenyu: true } },
      { jump: 'ending_beyond_pre' }
    ],

    /* ============================================================
     * 第二幕 · C线（离开）
     * 节拍：逃离 → 回忆反差（主题深化）→ 三年后真相追来 → 最终抉择
     * ============================================================ */
    leave_1: [
      { t: '我把信放回信箱，合上投信口。' },
      { t: '铁皮发出一声闷响。' },
      { say: '陈屿', text: '……就这样？', pose: 'surprise' },
      { say: '林砚', text: '就这样。' },
      { say: '林砚', text: '有些东西不是给我们这一届留的。' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { say: '陈屿', text: '你刚才为什么盯着那个信封看了那么久。', pose: 'sad' },
      { say: '林砚', text: '没有。' },
      { say: '陈屿', text: '你撒谎的样子，跟三年前一模一样。', pose: 'sad' },
      { jump: 'leave_2' }
    ],

    leave_2: [
      { bg: 'gate_morning', bgm: 'morning', weather: null },
      { hide: 'chenyu' },
      { t: '我们锁上门，下楼。' },
      { t: '走到校门口的时候，我回头看了一眼。' },
      { t: '四楼那个开着的窗口，像一只没有合上的眼睛。' },
      { bg: 'library_dusk', bgm: 'dusk' },
      { card: '第二章 · 后来的三年' },
      { t: '后来的三年，我确实毕业了。' },
      { t: '确实走远了。' },
      { t: '确实——很少抬头。' },
      { t: '高三那年，我进了重点班。' },
      { t: '老师说，林砚这孩子踏实，从不走神。' },
      { t: '他说得对。' },
      { t: '我从那以后再也没走过神。' },
      { t: '因为走神的时候，我会想起一件事。' },
      { t: '想起那天下午，我盯了那个信封很久。' },
      { t: '信封的角上有一小块水渍，干了，边缘发黄。' },
      { t: '三年前那场雨，把整栋楼都淋透了。' },
      { t: '可是那封信，是那天下午才投进去的。' },
      { t: '它怎么会干得那么快。' },
      { t: '——除非它早就干了。' },
      { t: '除非它不是三年前投进去的。' },
      { se: 'heartbeat' },
      { t: '这个问题我压了三年。' },
      { t: '压在每一个我没抬头的晚上。' },
      { jump: 'leave_3' }
    ],

    leave_3: [
      { bg: 'rooftop_dawn', bgm: 'mystic', weather: null },
      { t: '高三毕业那天，我又回了旧校舍。' },
      { t: '它已经开始拆了。' },
      { t: '西边的墙先倒下来，露出里面一格格空房间。' },
      { t: '像一排被拔掉牙的牙床。' },
      { show: 'chenyu', pose: 'sad', at: 'left' },
      { say: '陈屿', text: '我就知道你会来。', pose: 'sad' },
      { say: '林砚', text: '你怎么也来。' },
      { say: '陈屿', text: '……我也是压了三年。', pose: 'sad' },
      { say: '陈屿', text: '林砚，那天我没跟你说实话。', pose: 'sad' },
      { say: '陈屿', text: '我看见你盯着那个信封的时候，我也看见了。', pose: 'sad' },
      { say: '陈屿', text: '信封的日期，写的是三天前。', pose: 'sad' },
      { fx: 'shake' },
      { say: '林砚', text: '……你说什么？' },
      { say: '陈屿', text: '不是三年前。是三天前。', pose: 'sad' },
      { say: '陈屿', text: '当时我以为我看错了。', pose: 'sad' },
      { say: '陈屿', text: '后来我想了三年，越想越觉得自己没看错。', pose: 'sad' },
      { set: { knowDate: true } },
      { jump: 'leave_4' }
    ],

    leave_4: [
      { bg: 'mailbox_corner', bgm: 'tense' },
      { t: '我们撬开了天文台的门。' },
      { t: '里面的东西已经被搬空了。' },
      { t: '望远镜不在，星图不在，储物柜不在。' },
      { t: '只有那个信箱还在。' },
      { t: '它被人推到了墙角，锈得更厉害了。' },
      { say: '陈屿', text: '……还在。', pose: 'surprise' },
      { say: '林砚', text: '嗯。' },
      { se: 'mailbox' },
      { t: '投信口是开着的。' },
      { t: '里面有东西。' },
      { t: '不是那个牛皮纸信封。' },
      { t: '是另一封。' },
      { t: '很新。' },
      { t: '上面是我们刚才进来的那个日期。' },
      { fx: 'shake' },
      { say: '陈屿', text: '……今天。', pose: 'surprise' },
      { say: '林砚', text: '今天。' },
      { t: '我把那封信抽出来。' },
      { t: '信封上的字，是钢笔写的。' },
      { t: '字迹很轻，像是怕把纸划破：' },
      { t: '【致 三年后还愿意抬头看天的人】', style: 'letter' },
      { t: '落款：苏禾。' },
      { t: '日期：今天。' },
      { se: 'heartbeat' },
      { say: '陈屿', text: '……她在。', pose: 'surprise' },
      { say: '陈屿', text: '她一直在。', pose: 'surprise' },
      { say: '林砚', text: '不。' },
      { say: '林砚', text: '这是写给三年后的。' },
      { say: '林砚', text: '也就是说——' },
      { say: '林砚', text: '现在的我，是那封信的"三年前"。' },
      { jump: 'leave_5' }
    ],

    leave_5: [
      { bg: 'observatory_night', bgm: 'mystic', weather: 'stars' },
      { card: '第三章 · 第一次机会' },
      { t: '我们把它拆开了。' },
      { t: '这一次，是我主动的。' },
      { se: 'paper' },
      { t: '「如果你打开了这封信，说明这个世界上还有人愿意抬头。」', style: 'letter' },
      { t: '「我是苏禾。」', style: 'letter' },
      { t: '「我不知道这封信会落到谁手里。」', style: 'letter' },
      { t: '「但我知道，如果一个人愿意在拆信前犹豫很久——」', style: 'letter' },
      { t: '「那他一定见过上一封。」', style: 'letter' },
      { t: '「所以我写这封信，不是给陌生人的。」', style: 'letter' },
      { t: '「是给那个把它放回去的人。」', style: 'letter' },
      { fx: 'flash' },
      { show: 'suhe', pose: 'sad', at: 'center' },
      { say: '苏禾', text: '——三年了。' },
      { say: '陈屿', text: '!!', pose: 'surprise' },
      { say: '林砚', text: '学姐。' },
      { say: '苏禾', text: '不用叫学姐。' },
      { say: '苏禾', text: '三年前你把信放回去的时候，我以为你不会来了。', pose: 'sad' },
      { say: '林砚', text: '……对不起。' },
      { say: '苏禾', text: '不用说对不起。', pose: 'normal' },
      { say: '苏禾', text: '你只是没准备好。', pose: 'normal' },
      { say: '苏禾', text: '信这种东西，是要等一个刚好的时候的。' },
      { say: '苏禾', text: '早了读不懂，晚了就凉了。', pose: 'sad' },
      { say: '林砚', text: '那现在是刚好的时候吗？' },
      { say: '苏禾', text: '……', pose: 'sad' },
      { say: '苏禾', text: '现在是最后一班车。' },
      { say: '苏禾', text: '这栋楼还有一个星期就拆完了。', pose: 'sad' },
      { say: '苏禾', text: '三天后，信箱会被当废铁卖掉。' },
      { say: '苏禾', text: '我留在这里的时间，只剩三天。', pose: 'sad' },
      { set: { deadline: true } },
      { jump: 'leave_6' }
    ],

    leave_6: [
      { bg: 'rooftop_night', bgm: 'tense', weather: 'stars' },
      { hide: 'suhe' },
      { show: 'chenyu', pose: 'angry', at: 'left' },
      { say: '陈屿', text: '……你为什么现在才说。', pose: 'angry' },
      { show: 'suhe', pose: 'sad', at: 'right' },
      { say: '苏禾', text: '因为说了也没用。', pose: 'sad' },
      { say: '苏禾', text: '除非有人肯替我把信送出去。', pose: 'sad' },
      { say: '林砚', text: '送出去？送哪儿？' },
      { say: '苏禾', text: '三年后。', pose: 'normal' },
      { say: '苏禾', text: '我这封信，本来就是写给三年后的。', pose: 'normal' },
      { say: '苏禾', text: '但信箱不会自己走。' },
      { say: '苏禾', text: '要有人记着它，把它从废铁堆里捡回来。', pose: 'sad' },
      { say: '林砚', text: '……然后呢？' },
      { say: '苏禾', text: '然后等三年。', pose: 'sad' },
      { say: '苏禾', text: '等一个还愿意抬头的人来拆。' },
      { t: '这就是那个规则的背面。' },
      { t: '信箱不是一台机器。' },
      { t: '它需要一个活人替它记着。' },
      { say: '陈屿', text: '……你自己选吧，林砚。', pose: 'sad' },
      { say: '陈屿', text: '这次我不会拦你。', pose: 'sad' },
      { say: '陈屿', text: '只是，选了就别后悔。', pose: 'sad' },
      { t: '三天。' },
      { t: '我站在天台上，看着那颗叫星屑的星。' },
      { t: '它亮了三年，就为了等一个肯替它留下来的人。' },
      { t: '而我——' },
      { t: '我是那个三年前转身就走、三年后又回来的人。' },
      { t: '这一次，我得想清楚。' },
      { choice: {
          q: '——三天。你要怎么用？',
          options: [
            { text: '接下它。我把信箱搬走，替她等三年。', set: { leave_resolve: 'keep' }, goto: 'leave_keep' },
            { text: '不接。让她在最后三天，被好好看一次。', set: { leave_resolve: 'now' }, goto: 'leave_now' },
            { text: '把真相告诉陈屿，两个人一起记住。', set: { leave_resolve: 'share' }, goto: 'leave_share' },
            { text: '什么也不做。这一次，我还是走。', set: { leave_resolve: 'gone' }, goto: 'leave_gone' }
          ]
        } }
    ],

    /* --- C线第四分支：再一次离开（对应 closeddoor） --- */
    leave_gone: [
      { bg: 'mailbox_corner', bgm: 'tense', weather: null },
      { say: '苏禾', text: '……', pose: 'sad' },
      { say: '林砚', text: '对不起。' },
      { say: '林砚', text: '我做不到。' },
      { say: '苏禾', text: '我知道。', pose: 'sad' },
      { say: '苏禾', text: '三年前你就做不到。' },
      { say: '苏禾', text: '那句话你到现在都还没说出口。', pose: 'sad' },
      { t: '我张了张嘴。' },
      { t: '「那颗星还在。」' },
      { t: '六个字。' },
      { t: '我练了三年。' },
      { t: '还是没说出来。' },
      { fx: 'shake' },
      { say: '陈屿', text: '林砚！', pose: 'surprise' },
      { say: '陈屿', text: '你要去哪儿！' },
      { t: '我下了楼。' },
      { t: '楼梯很暗，我一步一步地走。' },
      { t: '走到二楼的时候，我听见顶楼传来一声很轻的响。' },
      { t: '像是什么东西，合上了。' },
      { se: 'mailbox' },
      { t: '我没有回头。' },
      { t: '一个星期后，旧校舍被推平。' },
      { t: '清理废墟的工人在顶楼发现一个锈死的铁信箱。' },
      { t: '里面有一封信。' },
      { t: '收信人写着"三年后还愿意抬头看天的人"。' },
      { t: '没人知道该怎么处理。' },
      { t: '最后它和那堆废铁一起，被送去了回收站。' },
      { hide: 'suhe' },
      { hide: 'chenyu' },
      { jump: 'ending_closeddoor_pre' }
    ],

    leave_keep: [
      { say: '苏禾', text: '……你要搬走它？', pose: 'surprise' },
      { say: '林砚', text: '嗯。' },
      { say: '林砚', text: '三年后，我会带着它回来。' },
      { say: '林砚', text: '到时候楼没了，但信箱还在。' },
      { say: '苏禾', text: '那你这三年怎么办。', pose: 'sad' },
      { say: '林砚', text: '……我不知道。' },
      { say: '林砚', text: '但我记得她问过一句话。' },
      { say: '林砚', text: '"那颗星还在吗。"' },
      { say: '林砚', text: '我想有一天，能亲口回答她。' },
      { say: '苏禾', text: '……', pose: 'sad' },
      { say: '苏禾', text: '好。', pose: 'normal' },
      { say: '苏禾', text: '那我等你三年。', pose: 'smile' },
      { set: { keeperChosen: true } },
      { jump: 'ending_unsigned_pre' }
    ],

    leave_now: [
      { say: '林砚', text: '不搬。' },
      { say: '林砚', text: '三天，够了。' },
      { say: '苏禾', text: '……', pose: 'surprise' },
      { say: '林砚', text: '你要的不是被搬走，是被看见。' },
      { say: '林砚', text: '那我们就在这三天里，把信读完。' },
      { say: '林砚', text: '一封一封，读给你听。' },
      { say: '苏禾', text: '……你疯了。', pose: 'sad' },
      { say: '苏禾', text: '箱里有四十七封。', pose: 'sad' },
      { say: '林砚', text: '那就三天不睡。' },
      { say: '陈屿', text: '……我陪你。', pose: 'normal' },
      { hide: 'suhe' },
      { bg: 'observatory_night', bgm: 'warm', weather: 'stars' },
      { t: '那三天，我们真的没睡。' },
      { t: '天亮之前读三封，中午读两封，入夜读五封。' },
      { t: '读到第九封的时候，苏禾开始跟着念。' },
      { t: '她的声音和我的叠在一起，像两个人在同一盏灯下看同一本书。' },
      { se: 'chime' },
      { t: '读到第三十封的时候，她不再出声了。' },
      { t: '我问她怎么了。' },
      { show: 'suhe', pose: 'smile', at: 'center' },
      { say: '苏禾', text: '没什么。', pose: 'smile' },
      { say: '苏禾', text: '只是发现……被读到的信，会变轻。' },
      { say: '苏禾', text: '轻到可以飘起来。', pose: 'smile' },
      { t: '第四十七封读完的那天凌晨，天刚蒙蒙亮。' },
      { t: '苏禾站在窗口，回头看我们。' },
      { say: '苏禾', text: '谢谢你们。', pose: 'smile' },
      { say: '苏禾', text: '这三年，我等的是有人肯把信读完。', pose: 'smile' },
      { say: '苏禾', text: '不是一个人——是两个人。' },
      { fx: 'flash' },
      { hide: 'suhe' },
      { t: '她没有了。' },
      { t: '不是消失。' },
      { t: '是终于不用再待在信封里了。' },
      { set: { readAll: true } },
      { jump: 'ending_beyond_pre' }
    ],

    leave_share: [
      { say: '林砚', text: '陈屿。' },
      { say: '林砚', text: '三年前那个下午，你也在楼下。' },
      { say: '陈屿', text: '……', pose: 'surprise' },
      { say: '林砚', text: '你在等一个人喊你。' },
      { say: '林砚', text: '她也在等一个人喊她。' },
      { say: '林砚', text: '你们两个人，隔了三层楼，等同一件事。' },
      { fx: 'shake' },
      { say: '陈屿', text: '……', pose: 'sad' },
      { say: '苏禾', text: '……', pose: 'sad' },
      { say: '林砚', text: '所以这次别等了。' },
      { say: '林砚', text: '陈屿，你有什么话，现在说。' },
      { t: '陈屿把相机举起来。' },
      { t: '这一次，他摘了镜头盖。' },
      { say: '陈屿', text: '学姐。', pose: 'sad' },
      { say: '陈屿', text: '……对不起，那天我没喊你。', pose: 'sad' },
      { say: '苏禾', text: '……', pose: 'cry' },
      { say: '苏禾', text: '没关系。', pose: 'smile' },
      { say: '苏禾', text: '你现在喊了。', pose: 'smile' },
      { se: 'chime' },
      { set: { calledOut: true } },
      { jump: 'ending_beyond_pre' }
    ],

    /* ============================================================
     * 第三幕 · 结局
     * ============================================================ */

    /* --- 真结局入口（前置：确认是否集齐条件） --- */
    ending_echo_pre: [
      { bg: 'starfield', bgm: 'ending', weather: 'stars' },
      { card: '三年后 · 六月的雨' },
      { t: '三年后的六月二十日，我收到了一封信。' },
      { t: '没有邮票，没有邮戳。' },
      { t: '信封上是我的字迹——是我自己三年前写的那封。' },
      { t: '我拆开它。' },
      { t: '里面除了我写的那张纸，还多了一张。' },
      { se: 'chime' },
      { t: '「林砚：」', style: 'letter' },
      { t: '「你写『在』这个字的时候，笔顿了一下。我听见了。」', style: 'letter' },
      { t: '「那颗星你没认错。周期确实是约三年——」', style: 'letter' },
      { t: '「因为我就是照着它的周期，把自己写进信箱的。」', style: 'letter' },
      { t: '「规则里没说的一件事是：」', style: 'letter' },
      { t: '「如果收信的人，肯把寄信的人写回来，那这封信就可以反着寄一次。」', style: 'letter' },
      { t: '「你做到了。所以现在轮到我来回答你了。」', style: 'letter' },
      { t: '「我也没有变成你害怕的那种大人。」', style: 'letter' },
      { t: '信的最后，画着一小片天区。' },
      { t: '是那张手绘星图的最后一页。' },
      { t: '星屑那颗星的旁边，被人用钢笔补了一行新的小字：' },
      { t: '【观测者：苏禾、林砚。下次合看：今年夏夜，旧天文台原址。】', style: 'letter' },
      { fx: 'flash' },
      { bg: 'lawn_summer', bgm: 'warm', weather: 'stars' },
      { t: '那天晚上，我真的去了。' },
      { t: '旧校舍的位置现在是一片草坪，草坪中央立着一张长椅。' },
      { t: '长椅旁边，有人支好了一台望远镜。' },
      { show: 'suhe', pose: 'smile', at: 'center' },
      { say: '苏禾', text: '——小学弟，你迟到了三分钟。' },
      { say: '林砚', text: '……学姐？' },
      { say: '苏禾', text: '嗯。我回来了。' },
      { say: '林砚', text: '怎么做到的。' },
      { say: '苏禾', text: '你把我的信，一个字一个字补回来了。', pose: 'smile' },
      { say: '苏禾', text: '三百二十七个字。你写了多久？' },
      { branch: [
          [function (s) { return s.companion === true; }, 'ending_echo_a'],
          'ending_echo_b'
        ] }
    ],

    ending_echo_a: [
      { say: '林砚', text: '三年。' },
      { say: '林砚', text: '还有一个人帮我配了三百二十七张照片。' },
      { show: 'chenyu', pose: 'smile', at: 'left' },
      { say: '陈屿', text: '——而且张张都看了。', pose: 'smile' },
      { say: '苏禾', text: '……你们俩。', pose: 'smile' },
      { jump: 'ending_echo_end' }
    ],

    ending_echo_b: [
      { say: '林砚', text: '三年。' },
      { say: '林砚', text: '每天一句，写完就来这里站一会儿。' },
      { say: '苏禾', text: '……一个人？', pose: 'sad' },
      { say: '林砚', text: '一个人。' },
      { say: '苏禾', text: '那很孤单吧。', pose: 'sad' },
      { say: '林砚', text: '不孤单。' },
      { say: '林砚', text: '因为我知道，你在读。' },
      { jump: 'ending_echo_end' }
    ],

    ending_echo_end: [
      { say: '苏禾', text: '望远镜我带来了。', pose: 'smile' },
      { say: '苏禾', text: '目镜还是老规矩，你来擦。' },
      { say: '林砚', text: '好。' },
      { t: '夏夜的风从草坪上滚过去。' },
      { t: '天顶偏南一点，有颗星很亮。' },
      { t: '它一直在那儿。' },
      { t: '只是今晚，有两个人一起看着它。' },
      { end: 'echo' }
    ],

    /* --- 隐藏结局 --- */
    ending_beyond_pre: [
      { bg: 'starfield', bgm: 'ending', weather: 'stars' },
      { card: '三年后 · 同一个夜里' },
      { t: '三年后的六月二十日。' },
      { t: '天文台原址的草坪上，多了一台旧信箱。' },
      { t: '绿色的漆掉得只剩斑块。' },
      { t: '投信口下面贴着一张纸：' },
      { t: '【星屑信箱 · 投信请注明年份】', style: 'letter' },
      { t: '那天晚上，信箱亮了四十七次。' },
      { se: 'chime' },
      { t: '每一次亮，都有一封空白的影子纸，从投信口里飘出来。' },
      { t: '飘到半空，变成一行字。' },
      { t: '然后散进夜里。' },
      { t: '「写给毕业的自己的」——被回答了。' },
      { t: '「写给去世的猫的」——被回答了。' },
      { t: '「写给三年前那个没说出口的人的」——被回答了。' },
      { t: '四十七封，一封不落。' },
      { bg: 'lawn_summer', bgm: 'warm', weather: 'stars' },
      { show: 'chenyu', pose: 'smile', at: 'left' },
      { show: 'hoshi', pose: 'cry', at: 'right' },
      { say: '？？？', text: '……我读完了。', pose: 'cry' },
      { say: '？？？', text: '原来被读到的感觉，是这样的。' },
      { say: '林砚', text: '你也要被读到一次。' },
      { say: '？？？', text: '我已经被读到了。', pose: 'smile' },
      { say: '？？？', text: '三年的日期，四十七个名字。' },
      { say: '？？？', text: '那是我的信。' },
      { say: '？？？', text: '你替我寄出去了。', pose: 'smile' },
      { branch: [
          [function (s) { return s.sentEcho === true; }, 'ending_beyond_echo' ],
          [function (s) { return s.calledOut === true; }, 'ending_beyond_called' ],
          'ending_beyond_readall'
        ] }
    ],

    /* 变体①：把空白的影子纸投进去（回声自己被读到） */
    ending_beyond_echo: [
      { say: '林砚', text: '那封信里没有字。' },
      { say: '林砚', text: '只有三年和四十七个日期。' },
      { say: '？？？', text: '嗯。' },
      { say: '？？？', text: '那是我唯一能写的东西。', pose: 'smile' },
      { say: '林砚', text: '够了。' },
      { say: '林砚', text: '有人等了三年，等的也不是字。' },
      { jump: 'ending_beyond_end' }
    ],

    /* 变体②：替两个隔了三层楼的人，把那声喊出来 */
    ending_beyond_called: [
      { show: 'chenyu', pose: 'smile', at: 'left' },
      { say: '陈屿', text: '……我拍了三年，第一次觉得照片是对的。', pose: 'smile' },
      { say: '林砚', text: '哪张。' },
      { say: '陈屿', text: '那张。' },
      { say: '陈屿', text: '她回头的那张。', pose: 'smile' },
      { say: '？？？', text: '……', pose: 'smile' },
      { say: '？？？', text: '原来被人叫住，是这种感觉。' },
      { jump: 'ending_beyond_end' }
    ],

    /* 变体③：三天不睡，把四十七封一封一封读完 */
    ending_beyond_readall: [
      { say: '林砚', text: '我们读了三天。' },
      { say: '林砚', text: '四十七封，一封没落下。' },
      { say: '？？？', text: '……我听见了。' },
      { say: '？？？', text: '每一封被你读出来的时候，我都在旁边。', pose: 'smile' },
      { say: '？？？', text: '那三天，是这三年里最长的。', pose: 'smile' },
      { say: '？？？', text: '也是最短的。' },
      { jump: 'ending_beyond_end' }
    ],

    ending_beyond_end: [
      { fx: 'flash' },
      { hide: 'hoshi' },
      { t: '我抬头。' },
      { t: '天顶偏南一点，那颗星比任何一次都亮。' },
      { t: '亮了一会儿，然后慢慢地，暗了下去。' },
      { say: '陈屿', text: '……它灭了。', pose: 'sad' },
      { say: '林砚', text: '不。' },
      { say: '林砚', text: '它只是不需要再亮给谁看了。' },
      { t: '有些星，是为了被等到才亮的。' },
      { t: '等到了，它就自由了。' },
      { t: '——包括我们自己。' },
      { end: 'beyond' }
    ],

    ending_unsent_pre: [
      { bg: 'gate_morning', bgm: 'morning', weather: 'sakura' },
      { card: '三年后 · 六月的操场' },
      { t: '三年后的六月，我大学毕业。' },
      { t: '那天下午我收拾宿舍。' },
      { t: '窗外的天很蓝，一朵云也没有。' },
      { t: '我忽然想起很久以前，有个学姐跟我说过：' },
      { t: '晴朗的白天其实也有星星，只是太阳太吵了，你听不见它们。' },
      { t: '我不知道为什么会想起这个。' },
      { t: '我放下手里的箱子，走到窗边，仰起头。' },
      { se: 'chime' },
      { t: '什么都没有。' },
      { t: '当然什么都没有——白天是看不见星星的。' },
      { t: '可我就那样仰着头，一直到脖子发酸。' },
      { t: '直到眼睛适应了那片空空的蓝。' },
      { t: '然后我看见了一行字。' },
      { t: '不是写在天上，是写在窗框的旧漆上。' },
      { t: '很小很小，像是谁用指甲刻的：' },
      { t: '【谢谢你写了那封信。虽然没有送到。】', style: 'letter' },
      { t: '我低下头。' },
      { t: '六月的天空很蓝，一朵云也没有。' },
      { t: '但那天下午，我在宿舍楼下的草坪上坐了很久很久。' },
      { t: '久到太阳偏西，久到第一颗星亮起来。' },
      { t: '我仰着头，一直到脖子发酸。' },
      { t: '——我还是那个会抬头的人。' },
      { t: '这就够了吧。我想。' },
      { t: '这大概就够了吧。' },
      { end: 'unsent' }
    ],

    ending_unsigned_pre: [
      { bg: 'observatory', bgm: 'dusk', weather: null },
      { card: '三年后 · 守箱人' },
      { t: '三年后，我把那个信箱搬到了新学校的顶楼。' },
      { t: '它比我想象中重。' },
      { t: '我叫了两个人，抬了三层楼。' },
      { t: '放下来的时候，其中一个问我：' },
      { t: '"这什么东西，值当吗。"' },
      { t: '我说值当。' },
      { t: '因为它里面还留着一张纸。' },
      { t: '一张写着"星屑"两个字的手绘星图。' },
      { t: '还有一支笔帽上贴着反光贴的笔。' },
      { se: 'chime' },
      { t: '后来也有人问过我，为什么要守着这个破箱子。' },
      { t: '我每次都答同一句：' },
      { t: '"因为总得有个人来关门。"' },
      { t: '其实还有半句我没说。' },
      { t: '——也总得有个人，替下一个愿意抬头的人，把灯留着。' },
      { bg: 'rooftop_night', bgm: 'mystic', weather: 'stars' },
      { t: '我学会了认星、擦目镜、修信箱的锁。' },
      { t: '我还学会了一件事：' },
      { t: '有些人不会回来。' },
      { t: '但他们会留在你替他们守着的那个地方。' },
      { t: '这就够了。' },
      { end: 'unsigned' }
    ],

    ending_closeddoor_pre: [
      { bg: 'gate_morning', bgm: 'morning', weather: null },
      { card: '很多年后' },
      { t: '旧校舍在第二年春天被推平。' },
      { t: '据说清理废墟的时候，工人在顶楼发现一个锈死的铁信箱。' },
      { t: '里面有一封信。' },
      { t: '收信人写着"三年后还愿意抬头看天的人"。' },
      { t: '没人知道该怎么处理。' },
      { t: '最后它和那堆废铁一起，被送去了回收站。' },
      { bg: 'library_dusk', bgm: 'dusk', weather: null },
      { t: '很多年后我偶尔会想起那天下午。' },
      { t: '想起那个我没敢拆开的信封。' },
      { t: '和那句我没能说出口的——' },
      { t: '「学姐，那颗星还在。」' },
      { t: '我现在的办公室有一整面落地窗。' },
      { t: '我每天在里面开会、签文件、看数据。' },
      { t: '从来没有抬头看过窗外。' },
      { t: '有一次加班到很晚，灯灭了一盏。' },
      { t: '我抬头看了一眼天花板。' },
      { t: '然后我发现，我已经想不起那颗星在哪个方向了。' },
      { t: '这不是一个悲伤的故事。' },
      { t: '这只是大部分夏天的样子。' },
      { end: 'closeddoor' }
    ]
  }
};

